### ISSUE TITLE
node-adodb on Debian

### ISSUE THREAD

**Issue by Spaarw** [nuintun/node-adodb#16]
Hello,

This package works really fine on my Windows 7, but I got an error on my Debian server when I try to do:
`var ADODB = require('node-adodb');`

This is the error:

`module.js:340
    throw err;
    ^
Error: Cannot find module 'node-adodb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/pegase/dbManager.js:12:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
`

Anyone can help ?

**Comment by nuintun** [comment]
Sorry,  because use Microsoft.Jet.OLEDB.4.0, so only support windows.
see:  https://github.com/nuintun/node-adodb/blob/master/lib/proxy.js#L19
