### ISSUE TITLE
Error: Spawn C:\Windows\SysWOW64\cscript.exe error

### ISSUE THREAD

**Issue by vulgodizz** [nuintun/node-adodb#323]
When I try to run a query in the database it presents the following error.

Error: Spawn C:\Windows\SysWOW64\cscript.exe error
at ChildProcess.<anonymous> (C:\app\node_modules\node-adodb\lib\spawn.js:120:37)
at ChildProcess.emit (events.js:210:5)
at ChildProcess.EventEmitter.emit (domain.js:475:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
exitMessage: undefined,
exitCode: 3221225794

I've tried everything, permission, quotes everything and it doesn't work

**Comment by nuintun** [comment]
Try run `sfc /scannow` ?

**Comment by vulgodizz** [comment]
Thank you very much, but I decided otherwise. I was using Amazon's ECS and migrated to an EC2. In EC2 it worked.
