### ISSUE TITLE
Error in query Select LIMIT

### ISSUE THREAD

**Issue by datdp** [nuintun/node-adodb#365]
I'm run false query 'SELECT * FROM TBWork ORDER BY W_PrgName ASC LIMIT 1' but I can run OK query 'SELECT * FROM TBWork ORDER BY W_PrgName ASC'

```
Error: Spawn C:\Windows\SysWOW64\cscript.exe error
	at ChildProcess.<anonymous> (D:\Project\MKTC\do_do_day_cat_vien_read_data\node_modules\node-adodb\lib\spawn.js:120:37)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
	process: { code: -2147217900, message: 'Syntax error in ORDER BY clause.' },
	exitCode: 0
	}
```

**Comment by Doise** [comment]
Are you using MS Access?
There is no `LIMIT` keyword in Access

**Comment by datdp** [comment]
I'm use MS access *.MDB
Thanks!

**Comment by SkeletonGamer** [comment]
Use `SELECT TOP 1 * FROM TBWork ORDER BY W_PrgName ASC;`
