### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by peterennis** [nuintun/node-adodb#38]
Running on Windows 10 x64.

What is the correct process to test this library using the examples
provided?

```
peter@Merry-Christmas MINGW64 /c/ae/ae-node-adodb/examples (aedev)
$ node --version
v8.6.0

peter@Merry-Christmas MINGW64 /c/ae/ae-node-adodb/examples (aedev)
$ npm --version
5.3.0

peter@Merry-Christmas MINGW64 /c/ae/ae-node-adodb/examples (aedev)
$
```

```
peter@Merry-Christmas MINGW64 /c/ae/ae-node-adodb (aedev)
$ cd examples

peter@Merry-Christmas MINGW64 /c/ae/ae-node-adodb/examples (aedev)
$ node execute.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ae\ae-node-adodb\lib\utils.js:4:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by nuintun** [comment]
Please use ```cmd``` or ```powershell``` run the test examples!
