### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by JasperPrune** [nuintun/node-adodb#42]
Have just installed node-adodb and am getting this error at the require statement

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/home/ubuntu/workspace/ILTProjectsV1/node_modules/node-adodb/lib/proxy.js:15:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

Process exited with code: 1

**Comment by nuintun** [comment]
This lib required Microsoft ADO and cscript, do not support linux!
