### ISSUE TITLE
Error:  Arguments are of the wrong type, are out of acceptable range

### ISSUE THREAD

**Issue by samlee22** [nuintun/node-adodb#48]
Hi Nuitun, 

I tried the adodb on windows with an MsAccess mdb file and I got the following errors.
Do you know what it could be?

const ADODB = require('node-adodb');
const connection = ADODB.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=att3000.mdb;');

 async function query() {
  try {
	 console.log('go!');
    const users = await connection.query('SELECT * FROM userinfo');
 
    console.log(JSON.stringify(users, null, 2));

  } catch (error) {
    console.error(error);
  }
}
query();

Error: Arguments are of the wrong type, are out of acceptable range, or are in conflict with one another.
    at Socket.stdio.stderr.on.data (C:\axe\node_modules\node-adodb\lib\proxy.js:50:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onread (net.js:587:20)

**Comment by nuintun** [comment]
This message returned by Microsoft.Jet.OLEDB.4.0, please check your database~
